### ISSUE TITLE
ES6 kode naudojam template literals

### ISSUE THREAD

**Issue by minvs1** [Justez/Rails-5-blog#1]
https://github.com/Justez/Rails-5-blog/blob/10da0b98a1a17a4f503cc9e78fd8025424ce2950/app/assets/javascripts/views/posts/main.es6#L24

Patogumo dėlei naudojam [Template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)

**Comment by Justez** [comment]
fixed
